apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1tt0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-aqul-tenant/rhtap-demo-app/hacbs-test-project-1tt0@sha256:b7bb1697f4d3cd1fdf08557c10a634d78e05ff37a524c05887e33ab62e4b53b9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
