apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1tt0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-aqul-tenant/rhtap-demo-app/hacbs-test-project-1tt0@sha256:47e81566b35c6a07a3a7cc3f630ddc201c385ce5516cfde58b958f1be22bc99f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
